"""empty message

Revision ID: 3858211d8204
Revises: bdde9922544e
Create Date: 2025-09-24 17:35:17.144632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3858211d8204'
down_revision = 'bdde9922544e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.String(length=15), nullable=True))
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.drop_column('hair_color')

    # ### end Alembic commands ###
